import { calculateCraftProject } from '../utils/craftCalculations.js';
import { formatCompactKamas, formatKamas, formatNumber } from '../../../utils/currency.js';
import { escapeHtml, icon, imageTag, t } from '../../../components/common.js';
import { renderBreadcrumbs } from '../../../components/breadcrumbs.js';

function searchResults(state) {
  const search=state.craftSearch||{};
  if(search.status==='loading')return `<div class="combobox-empty">${escapeHtml(t(state,'common.loading'))}</div>`;
  if(search.error)return `<div class="combobox-empty error-text">${escapeHtml(t(state,'v3.crafts.apiUnavailable'))}</div>`;
  if(!search.results.length)return `<div class="combobox-empty">${escapeHtml(search.query?t(state,'common.noResults'):t(state,'v3.crafts.searchHint'))}</div>`;
  return search.results.map(item=>`<button type="button" class="combobox-option item-option" data-action="select-craft-item" data-id="${item.ankamaId}" data-category="${escapeHtml(item.category)}">${imageTag(item.imageUrl,item.name,'combobox-thumb')}<span><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.type)} · ${escapeHtml(t(state,'simulation.levelShort'))} ${formatNumber(item.level)}</small></span></button>`).join('');
}

function ingredientRow(state,line,index){
  return `<article class="ingredient-row" data-ingredient-id="${escapeHtml(line.id)}"><div class="ingredient-main">${imageTag(line.imageSnapshot,line.nameSnapshot,'ingredient-thumb')}<div><strong>${escapeHtml(line.nameSnapshot)}</strong><small>${formatNumber(line.quantityPerUnit)} × ${escapeHtml(t(state,'v3.crafts.perUnit'))} · ${formatNumber(line.totalQuantity)} ${escapeHtml(t(state,'v3.crafts.total'))}</small></div></div><label class="field compact-field"><span>${escapeHtml(t(state,'v3.crafts.acquisition'))}</span><select class="select" data-craft-ingredient-field="acquisitionMode" data-id="${escapeHtml(line.id)}"><option value="buy" ${line.acquisitionMode==='buy'?'selected':''}>${escapeHtml(t(state,'v3.crafts.buy'))}</option><option value="stock" ${line.acquisitionMode==='stock'?'selected':''}>${escapeHtml(t(state,'v3.crafts.useStock'))}</option><option value="craft" ${line.acquisitionMode==='craft'?'selected':''}>${escapeHtml(t(state,'v3.crafts.manufacture'))}</option></select></label><label class="field compact-field"><span>${escapeHtml(t(state,'v3.crafts.unitPrice'))}</span><input class="input" inputmode="numeric" data-craft-ingredient-field="unitMarketPrice" data-id="${escapeHtml(line.id)}" value="${line.unitMarketPrice||''}"></label><label class="field compact-field"><span>${escapeHtml(t(state,'v3.crafts.stockUse'))}</span><input class="input" inputmode="numeric" data-craft-ingredient-field="useStockQuantity" data-id="${escapeHtml(line.id)}" value="${line.useStockQuantity||''}"></label><div class="ingredient-actions">${line.acquisitionMode==='craft'?`<button class="button ghost compact" data-action="load-subrecipe" data-id="${escapeHtml(line.id)}">${icon('craft',15)} ${escapeHtml(t(state,'v3.crafts.loadSubrecipe'))}</button>`:''}<button class="icon-button danger" data-action="remove-craft-ingredient" data-id="${escapeHtml(line.id)}" aria-label="${escapeHtml(t(state,'common.delete'))}">${icon('trash',16)}</button></div>${line.subRecipe?.length?`<div class="subrecipe-summary"><strong>${escapeHtml(t(state,'v3.crafts.subrecipe'))}</strong><span>${line.subRecipe.map(sub=>`${formatNumber(sub.quantityPerUnit)} × ${escapeHtml(sub.nameSnapshot)}`).join(' · ')}</span></div>`:''}</article>`;
}

export function renderCraftProjectEditor(state) {
  const editor=state.craftEditor;
  if(!editor)return '';
  const project=editor.project;
  const calc=calculateCraftProject(project);
  project.financialCost=Math.round(calc.financialCost);project.economicCost=Math.round(calc.economicCost);project.accountingCost=Math.round(calc.accountingCost);project.replacementCost=Math.round(calc.economicCost);
  return `<section class="stack">${renderBreadcrumbs(state,[{label:t(state,'v3.modules.crafts.title'),route:'crafts'},{label:t(state,'v3.crafts.projects'),route:'craft-projects'},{label:project.itemNameSnapshot||t(state,'v3.crafts.newProject')}])}<div class="section-head"><div><span class="eyebrow">${escapeHtml(t(state,'v3.crafts.projectEditor'))}</span><h1>${escapeHtml(editor.mode==='new'?t(state,'v3.crafts.newProject'):project.itemNameSnapshot)}</h1><p>${escapeHtml(t(state,'v3.crafts.editorDescription'))}</p></div><button class="button ghost" data-action="exit-craft-editor">${icon('back',17)} ${escapeHtml(t(state,'common.back'))}</button></div>
    <div class="craft-editor-layout"><div class="stack">
      <article class="card section"><h2>${escapeHtml(t(state,'v3.crafts.chooseItem'))}</h2><div class="craft-item-selector"><label class="field"><span>${escapeHtml(t(state,'v3.crafts.searchItem'))}</span><div class="combobox"><input class="input" autocomplete="off" data-craft-item-search value="${escapeHtml(editor.itemQuery||'')}" placeholder="${escapeHtml(t(state,'v3.crafts.searchPlaceholder'))}" aria-controls="craft-item-options" aria-expanded="${Boolean(editor.searchOpen)}"><div id="craft-item-options" class="combobox-options" role="listbox" ${editor.searchOpen?'':'hidden'}>${searchResults(state)}</div></div></label>${project.ankamaId?`<div class="selected-craft-item">${imageTag(project.itemImageSnapshot,project.itemNameSnapshot,'selected-item-image')}<div><strong>${escapeHtml(project.itemNameSnapshot)}</strong><small>${escapeHtml(project.itemTypeSnapshot)} · ${escapeHtml(t(state,'simulation.levelShort'))} ${formatNumber(project.itemLevelSnapshot)}</small></div></div>`:''}</div></article>
      <article class="card section"><h2>${escapeHtml(t(state,'v3.crafts.plan'))}</h2><div class="form-grid four"><label class="field"><span>${escapeHtml(t(state,'v3.crafts.quantity'))}</span><input class="input" inputmode="numeric" data-craft-field="desiredQuantity" value="${project.desiredQuantity||''}"></label><label class="field"><span>${escapeHtml(t(state,'v3.crafts.finishedMarketPrice'))}</span><input class="input" inputmode="numeric" data-craft-field="marketUnitPrice" value="${project.marketUnitPrice||''}"></label><label class="field"><span>${escapeHtml(t(state,'v3.crafts.desiredSalePrice'))}</span><input class="input" inputmode="numeric" data-craft-field="desiredSalePrice" value="${project.desiredSalePrice||''}"></label><label class="field"><span>${escapeHtml(t(state,'v3.crafts.additionalCosts'))}</span><input class="input" inputmode="numeric" data-craft-field="additionalCosts" value="${project.additionalCosts||''}"></label><label class="field"><span>${escapeHtml(t(state,'v3.crafts.saleChannel'))}</span><select class="select" data-craft-field="saleChannel"><option value="HDV" ${project.saleChannel==='HDV'?'selected':''}>HDV</option><option value="Venda direta" ${project.saleChannel==='Venda direta'?'selected':''}>${escapeHtml(t(state,'v3.sales.direct'))}</option></select></label><label class="field"><span>${escapeHtml(t(state,'v3.crafts.costingMethod'))}</span><select class="select" data-craft-field="costingMethod"><option value="weighted_average" ${project.costingMethod==='weighted_average'?'selected':''}>${escapeHtml(t(state,'v3.crafts.weightedAverage'))}</option><option value="financial" ${project.costingMethod==='financial'?'selected':''}>${escapeHtml(t(state,'v3.crafts.financialCost'))}</option></select></label><label class="field span-2"><span>${escapeHtml(t(state,'v3.crafts.notes'))}</span><input class="input" data-craft-field="notes" value="${escapeHtml(project.notes||'')}"></label></div></article>
      <article class="card section"><div class="section-head compact-head"><div><h2>${escapeHtml(t(state,'v3.crafts.ingredients'))}</h2><p>${escapeHtml(t(state,'v3.crafts.ingredientsHelp'))}</p></div></div>${project.ingredients.length?`<div class="ingredient-list">${calc.ingredients.map((line,index)=>ingredientRow(state,line,index)).join('')}</div>`:`<div class="empty-inline">${escapeHtml(project.ankamaId?t(state,'v3.crafts.noRecipe'):t(state,'v3.crafts.chooseItemFirst'))}</div>`}</article>
    </div><aside class="stack sticky craft-summary"><article class="card section"><span class="eyebrow">${escapeHtml(t(state,'v3.crafts.summary'))}</span><dl class="summary-list"><div><dt>${escapeHtml(t(state,'v3.crafts.financialCost'))}</dt><dd>${formatKamas(calc.financialCost)}</dd></div><div><dt>${escapeHtml(t(state,'v3.crafts.economicCost'))}</dt><dd>${formatKamas(calc.economicCost)}</dd></div><div><dt>${escapeHtml(t(state,'v3.crafts.unitCost'))}</dt><dd>${formatKamas(calc.unitAccountingCost)}</dd></div><div><dt>${escapeHtml(t(state,'v3.crafts.marketBuyCost'))}</dt><dd>${project.marketUnitPrice?formatKamas(calc.marketBuyCost):'—'}</dd></div><div><dt>${escapeHtml(t(state,'v3.metrics.potentialProfit'))}</dt><dd class="${calc.potentialProfitEconomic<0?'negative':'positive'}">${formatKamas(calc.potentialProfitEconomic)}</dd></div><div><dt>${escapeHtml(t(state,'v3.crafts.margin'))}</dt><dd>${formatNumber(calc.potentialMargin,1)}%</dd></div><div><dt>ROI</dt><dd>${formatNumber(calc.roi,1)}%</dd></div></dl>${calc.missingPrices.length?`<div class="notice warning">${escapeHtml(t(state,'v3.crafts.missingPrices',{count:calc.missingPrices.length}))}</div>`:''}<div class="stack-actions"><button class="button primary" data-action="save-craft-project">${icon('check',17)} ${escapeHtml(t(state,'v3.crafts.saveProject'))}</button>${editor.mode!=='new'?`<button class="button secondary" data-action="complete-craft-project" data-id="${escapeHtml(project.id)}">${escapeHtml(t(state,'v3.crafts.completeProduction'))}</button>`:''}</div></article></aside></div>
  </section>`;
}
