import { MAX_LEVEL } from '../data/xpTable.js';
import { creatureCatalog, getCreatureById, getCreatureName } from '../data/creatures.js';
import { feedingResources, getFeedingResourceName, searchFeedingResources } from '../data/feedingResources.js';
import { calculateSimulation, getLevelXpLimit } from '../utils/calculations.js';
import { formatCompactKamas, formatNumber } from '../utils/currency.js';
import { includesNormalized } from '../utils/textSearch.js';
import { escapeHtml, icon, imageTag, t } from './common.js';

export const methodKey = { vitaminizedFood:'marketFood', kolitokenBag:'kolitokenBag', resources:'resources', combined:'combined' };

function fieldError(editor, key, state) {
  const errorKey = editor.errors?.[key];
  return errorKey ? `<span class="error" id="error-${key}">${escapeHtml(t(state,`simulation.validation.${errorKey}`))}</span>` : '';
}

function renderStepper(state, editor) {
  const labels = ['creature','levels','method','costs','review'];
  return `<div class="stepper" aria-label="${escapeHtml(t(state,'simulation.stepLabel',{current:editor.step,total:5}))}">${labels.map((key,index)=>{
    const step=index+1; const cls=step===editor.step?'active':step<editor.step?'complete':'';
    return `<button class="step ${cls}" data-action="go-step" data-step="${step}" ${step>editor.maxReached?'disabled':''} ${step===editor.step?'aria-current="step"':''}><span>${step<editor.step?'✓':step}</span><strong>${escapeHtml(t(state,`simulation.steps.${key}`))}</strong></button>`;
  }).join('')}</div>`;
}

function renderCreatureStep(state, editor) {
  const sim=editor.simulation;
  const selected=getCreatureById(sim.creatureId);
  const filtered=creatureCatalog.filter(c=>c.type===sim.creatureType && [getCreatureName(c,state.language),c.canonicalName,...Object.values(c.names||{})].some(name=>includesNormalized(name,editor.creatureQuery||''))).slice(0,18);
  return `<div class="stack"><div class="form-grid">
    <label class="field" for="creature-type"><span>${escapeHtml(t(state,'simulation.creatureType'))}</span><select class="select" id="creature-type" data-field="creatureType"><option value="Mascote" ${sim.creatureType==='Mascote'?'selected':''}>${escapeHtml(t(state,'simulation.pet'))}</option><option value="Montascote" ${sim.creatureType==='Montascote'?'selected':''}>${escapeHtml(t(state,'simulation.petsmount'))}</option></select></label>
    <div class="field creature-combobox"><label for="creature-search">${escapeHtml(t(state,'simulation.species'))}</label><div class="input-wrap"><input class="input" id="creature-search" data-field="creatureQuery" role="combobox" aria-expanded="${editor.comboOpen?'true':'false'}" aria-controls="creature-options" aria-autocomplete="list" autocomplete="off" value="${escapeHtml(editor.comboOpen ? editor.creatureQuery : (editor.creatureQuery || getCreatureName(selected,state.language)))}" placeholder="${escapeHtml(t(state,'simulation.searchCreature'))}" aria-invalid="${Boolean(editor.errors?.creatureId)}"><span class="suffix">${icon('search',17)}</span></div>
    ${editor.comboOpen?`<div class="combobox-list" id="creature-options" role="listbox">${filtered.length?filtered.map((c,i)=>`<button class="combobox-option" type="button" role="option" aria-selected="${c.id===sim.creatureId}" data-action="select-creature" data-id="${c.id}" data-index="${i}">${imageTag(c.imageUrl,getCreatureName(c,state.language))}<span><strong>${escapeHtml(getCreatureName(c,state.language))}</strong><small class="muted">${escapeHtml(c.type==='Mascote'?t(state,'simulation.pet'):t(state,'simulation.petsmount'))}</small></span></button>`).join(''):`<p class="small muted" style="padding:12px">${escapeHtml(t(state,'common.noResults'))}</p>`}</div>`:''}
    ${fieldError(editor,'creatureId',state)}</div>
    <label class="field" for="simulation-name"><span>${escapeHtml(t(state,'simulation.simulationName'))}</span><input class="input" id="simulation-name" data-field="name" value="${escapeHtml(sim.name)}"><small>${escapeHtml(t(state,'simulation.autoNameHint'))}</small></label>
  </div>${selected?`<div class="selected-creature">${imageTag(selected.imageUrl,getCreatureName(selected,state.language),'creature-thumb large')}<div><span class="eyebrow">${escapeHtml(t(state,'simulation.selectedCreature'))}</span><h2>${escapeHtml(getCreatureName(selected,state.language))}</h2><p class="muted">${escapeHtml(selected.canonicalName)} · ${escapeHtml(selected.type==='Mascote'?t(state,'simulation.pet'):t(state,'simulation.petsmount'))}</p></div></div>`:''}</div>`;
}

function renderLevelsStep(state, editor, calc) {
  const sim=editor.simulation; const max=getLevelXpLimit(sim.originLevel);
  return `<div class="stack"><div class="form-grid three">
    <label class="field" for="origin-level"><span>${escapeHtml(t(state,'simulation.originLevel'))}</span><input class="input" id="origin-level" data-field="originLevel" type="number" min="0" max="99" value="${sim.originLevel}" aria-invalid="${Boolean(editor.errors?.originLevel)}">${fieldError(editor,'originLevel',state)}</label>
    <label class="field" for="current-xp"><span>${escapeHtml(t(state,'simulation.currentXp'))} <small>${escapeHtml(t(state,'common.optional'))}</small></span><input class="input" id="current-xp" data-field="currentXp" type="number" min="0" max="${max}" value="${sim.currentXp||''}" placeholder="${escapeHtml(t(state,'simulation.currentXpHint',{max:formatNumber(max,state.language,2)}))}"></label>
    <label class="field" for="target-level"><span>${escapeHtml(t(state,'simulation.targetLevel'))}</span><input class="input" id="target-level" data-field="targetLevel" type="number" min="1" max="${MAX_LEVEL}" value="${sim.targetLevel}" aria-invalid="${Boolean(editor.errors?.targetLevel)}">${fieldError(editor,'targetLevel',state)}</label>
  </div><div class="card section" style="background:var(--surface-blue)"><span class="eyebrow">${escapeHtml(t(state,'simulation.requiredXp'))}</span><strong style="display:block;font-size:2rem;margin-top:6px">${formatNumber(calc.xpNeeded,state.language,2)} XP</strong><p class="muted">${escapeHtml(t(state,'simulation.levelRange',{origin:sim.originLevel,target:sim.targetLevel}))}</p></div></div>`;
}

function methodQuantity(state, method, id) {
  if(id==='combined') return t(state,'simulation.combinedQuantity',{resources:method.resourceQuantity,rations:method.rationQuantity});
  return String(method.quantity);
}

function methodCard(state, sim, calc, id) {
  const m=calc.methods[id]; const selected=sim.upMethod===id; const cheapest=calc.cheapest===id;
  return `<button type="button" class="method-card ${selected?'selected':''} ${cheapest?'cheapest':''}" ${cheapest?`data-cheapest="${escapeHtml(t(state,'simulation.cheapest'))}"`:''} data-action="select-method" data-method="${id}" aria-pressed="${selected}"><h3>${escapeHtml(t(state,`simulation.${methodKey[id]}`))}</h3><div class="method-stats"><div><span>${escapeHtml(t(state,'simulation.quantityNeeded'))}</span><strong>${escapeHtml(methodQuantity(state,m,id))}</strong></div><div><span>${escapeHtml(t(state,'simulation.xpObtained'))}</span><strong>${formatNumber(m.xpObtained,state.language,2)} XP</strong></div><div><span>${escapeHtml(t(state,'simulation.totalCost'))}</span><strong>${formatCompactKamas(m.totalCost,state.language)}</strong></div><div><span>${escapeHtml(t(state,'simulation.costPerXp'))}</span><strong>${formatNumber(m.costPerXp,state.language,2)} K</strong></div></div>${id==='combined'?`<small class="muted">${escapeHtml(t(state,'simulation.combinedSummary',{resourceXp:formatNumber(m.resourceXp,state.language,2),remainingXp:formatNumber(m.remainingXp,state.language,2)}))}</small>`:''}${!m.sufficient?`<span class="badge red">${escapeHtml(t(state,'simulation.insufficientXp'))}</span>`:''}</button>`;
}

function resourceOptions(state, editor) {
  const filtered=searchFeedingResources(editor.resourceQuery||'',state.language,45);
  return filtered.map(item=>`<option value="${item.id}">${escapeHtml(getFeedingResourceName(item,state.language))} · ${formatNumber(item.xp,state.language,3)} XP</option>`).join('');
}

function lineResourceOptions(state, currentId) {
  return feedingResources.map(item=>`<option value="${item.id}" ${item.id===currentId?'selected':''}>${escapeHtml(getFeedingResourceName(item,state.language))} · ${formatNumber(item.xp,state.language,3)} XP</option>`).join('');
}

function renderResourceLine(state, line) {
  const resourceCell=line.custom
    ? `<div class="resource-edit-stack"><input class="input" value="${escapeHtml(line.canonicalName)}" data-resource-field="customName" data-id="${line.id}" aria-label="${escapeHtml(t(state,'simulation.resourceName'))}"><small class="muted">${escapeHtml(t(state,'simulation.customResource'))}</small></div>`
    : `<select class="select resource-line-select" data-resource-field="resourceId" data-id="${line.id}" aria-label="${escapeHtml(t(state,'simulation.resource'))}">${lineResourceOptions(state,line.resourceId)}</select>`;
  const xpCell=line.custom
    ? `<input class="input" style="min-width:100px" type="number" min="0.0001" step="0.001" value="${line.xpUnit}" data-resource-field="customXp" data-id="${line.id}" aria-label="${escapeHtml(t(state,'simulation.unitXp'))}">`
    : formatNumber(line.xpUnit,state.language,3);
  return `<tr><td>${resourceCell}</td><td>${xpCell}</td><td><input class="input" style="min-width:80px" type="number" min="1" value="${line.quantity}" data-resource-field="quantity" data-id="${line.id}"></td><td>${formatNumber(line.xpTotal,state.language,3)}</td><td><input class="input" style="min-width:120px" inputmode="numeric" value="${line.unitPrice}" data-resource-field="unitPrice" data-id="${line.id}"></td><td>${formatCompactKamas(line.costTotal,state.language)}</td><td><button class="icon-button" type="button" data-action="delete-resource" data-id="${line.id}" aria-label="${escapeHtml(t(state,'common.delete'))}">${icon('trash',17)}</button></td></tr>`;
}

function renderResourceEditor(state, editor, calc) {
  const r=calc.resources;
  const coverage=calc.xpNeeded>0?Math.min(100,r.xpObtained/calc.xpNeeded*100):100;
  return `<div class="collapsible"><button type="button" class="collapsible-trigger" data-action="toggle-resources" aria-expanded="${editor.resourcesOpen}"><span><strong>${escapeHtml(t(state,'simulation.resourcePanel'))}</strong><small class="muted" style="display:block">${escapeHtml(t(state,'simulation.resourcesCount',{count:r.lines.length}))} · ${escapeHtml(t(state,'simulation.resourcesXp',{xp:formatNumber(r.xpObtained,state.language,2)}))} · ${formatCompactKamas(r.totalCost,state.language)}</small></span>${icon(editor.resourcesOpen?'down':'chevron')}</button>${editor.resourcesOpen?`<div class="collapsible-content stack">
    <div class="resource-coverage"><div><span>${escapeHtml(t(state,'simulation.resourceCoverage'))}</span><strong>${formatNumber(coverage,state.language,1)}%</strong></div><div class="coverage-track"><span style="width:${coverage}%"></span></div><small>${escapeHtml(t(state,'simulation.remainingXp'))}: ${formatNumber(r.remainingXp,state.language,2)} XP</small></div>
    <div class="resource-search-row"><label class="field"><span>${escapeHtml(t(state,'simulation.searchResource'))}</span><input class="input" data-resource-search value="${escapeHtml(editor.resourceQuery||'')}" placeholder="${escapeHtml(t(state,'simulation.searchResourceHint'))}"></label><button class="button secondary" type="button" data-action="toggle-custom-resource">${icon('plus',17)} ${escapeHtml(t(state,'simulation.customResource'))}</button></div>
    ${editor.customResourceOpen?`<div class="custom-resource-box"><div class="form-grid three"><label class="field"><span>${escapeHtml(t(state,'simulation.resourceName'))}</span><input class="input" data-resource-new="customName"></label><label class="field"><span>${escapeHtml(t(state,'simulation.unitXp'))}</span><input class="input" data-resource-new="customXp" type="number" min="0.0001" step="0.001"></label><label class="field"><span>${escapeHtml(t(state,'simulation.quantity'))}</span><input class="input" data-resource-new="customQuantity" type="number" min="1" value="1"></label></div><label class="field"><span>${escapeHtml(t(state,'simulation.unitPrice'))}</span><input class="input" data-resource-new="customUnitPrice" inputmode="numeric" value="0"></label><button class="button secondary" type="button" data-action="add-custom-resource">${escapeHtml(t(state,'simulation.addResource'))}</button></div>`:''}
    <div class="resource-add"><label class="field"><span>${escapeHtml(t(state,'simulation.resource'))}</span><select class="select" data-resource-new="resourceId"><option value="">—</option>${resourceOptions(state,editor)}</select></label><label class="field"><span>${escapeHtml(t(state,'simulation.quantity'))}</span><input class="input" data-resource-new="quantity" type="number" min="1" value="1"></label><label class="field"><span>${escapeHtml(t(state,'simulation.unitPrice'))}</span><input class="input" data-resource-new="unitPrice" inputmode="numeric" value="0"></label><button class="button secondary" type="button" data-action="add-resource">${icon('plus',17)} ${escapeHtml(t(state,'simulation.addResource'))}</button></div>
    <div data-resource-error class="error"></div><div class="table-wrap"><table class="resource-table"><thead><tr><th>${escapeHtml(t(state,'simulation.resource'))}</th><th>${escapeHtml(t(state,'simulation.unitXp'))}</th><th>${escapeHtml(t(state,'simulation.quantity'))}</th><th>${escapeHtml(t(state,'simulation.totalXp'))}</th><th>${escapeHtml(t(state,'simulation.unitPrice'))}</th><th>${escapeHtml(t(state,'simulation.lineCost'))}</th><th>${escapeHtml(t(state,'common.actions'))}</th></tr></thead><tbody>${r.lines.length?r.lines.map(line=>renderResourceLine(state,line)).join(''):`<tr><td colspan="7" class="muted" style="text-align:center;padding:24px">${escapeHtml(t(state,'common.noResults'))}</td></tr>`}</tbody></table></div><div class="resource-summary"><span>${escapeHtml(t(state,'simulation.quantity'))}: <strong>${r.quantity}</strong></span><span>${escapeHtml(t(state,'simulation.totalXp'))}: <strong>${formatNumber(r.xpObtained,state.language,2)}</strong></span><span>${escapeHtml(t(state,'simulation.totalCost'))}: <strong>${formatCompactKamas(r.totalCost,state.language)}</strong></span><span>${escapeHtml(t(state,'simulation.averageCostXp'))}: <strong>${formatNumber(r.costPerXp,state.language,2)} K</strong></span></div></div>`:''}</div>`;
}

function renderCombinedConfigurator(state, sim, calc) {
  if(sim.upMethod!=='combined')return '';
  const m=calc.methods.combined;
  return `<section class="combined-config card section"><div><span class="eyebrow">${escapeHtml(t(state,'simulation.combined'))}</span><h3>${escapeHtml(t(state,'simulation.combinedHelpTitle'))}</h3><p class="muted small">${escapeHtml(t(state,'simulation.combinedHelp'))}</p></div><div class="combined-flow"><div><span>${escapeHtml(t(state,'simulation.resources'))}</span><strong>${formatNumber(m.resourceXp,state.language,2)} XP</strong></div><span class="flow-arrow">+</span><div><span>${escapeHtml(t(state,'simulation.rationComplement'))}</span><strong>${formatNumber(m.remainingXp,state.language,2)} XP</strong></div><span class="flow-arrow">=</span><div><span>${escapeHtml(t(state,'simulation.xpObtained'))}</span><strong>${formatNumber(m.xpObtained,state.language,2)} XP</strong></div></div><fieldset class="field"><legend>${escapeHtml(t(state,'simulation.complementSource'))}</legend><div class="grid-2"><label class="compact-choice ${sim.combinedRationSource==='vitaminizedFood'?'selected':''}"><input type="radio" name="combined-source" data-field="combinedRationSource" value="vitaminizedFood" ${sim.combinedRationSource==='vitaminizedFood'?'checked':''}><strong>${escapeHtml(t(state,'simulation.marketFood'))}</strong></label><label class="compact-choice ${sim.combinedRationSource==='kolitokenBag'?'selected':''}"><input type="radio" name="combined-source" data-field="combinedRationSource" value="kolitokenBag" ${sim.combinedRationSource==='kolitokenBag'?'checked':''}><strong>${escapeHtml(t(state,'simulation.kolitokenBag'))}</strong></label></div></fieldset></section>`;
}

function renderMethodStep(state, editor, calc) {
  const sim=editor.simulation;
  return `<div class="stack"><p class="muted">${escapeHtml(t(state,'simulation.chooseMethod'))}</p><div class="form-grid"><label class="field"><span>${escapeHtml(t(state,'simulation.marketFoodPrice'))}</span><div class="input-wrap"><input class="input" data-field="marketFoodPrice" inputmode="numeric" value="${sim.marketFoodPrice||''}" placeholder="0"><span class="suffix">K</span></div></label><label class="field"><span>${escapeHtml(t(state,'simulation.bagPrice'))}</span><div class="input-wrap"><input class="input" data-field="bagPrice" inputmode="numeric" value="${sim.bagPrice||''}" placeholder="0"><span class="suffix">K</span></div></label></div><div class="method-grid">${['vitaminizedFood','kolitokenBag','resources','combined'].map(id=>methodCard(state,sim,calc,id)).join('')}</div>${fieldError(editor,'upMethod',state)}${fieldError(editor,'marketFoodPrice',state)}${fieldError(editor,'bagPrice',state)}${fieldError(editor,'resources',state)}${renderCombinedConfigurator(state,sim,calc)}${renderResourceEditor(state,editor,calc)}</div>`;
}

function renderCostsStep(state, editor, calc) {
  const sim=editor.simulation;
  return `<div class="stack"><div class="form-grid three"><label class="field"><span>${escapeHtml(t(state,'simulation.originCost'))}</span><div class="input-wrap"><input class="input" data-field="originCost" inputmode="numeric" value="${sim.originCost||''}" aria-invalid="${Boolean(editor.errors?.originCost)}"><span class="suffix">K</span></div>${fieldError(editor,'originCost',state)}</label><label class="field"><span>${escapeHtml(t(state,'simulation.additionalCosts'))} <small>${escapeHtml(t(state,'common.optional'))}</small></span><div class="input-wrap"><input class="input" data-field="additionalCosts" inputmode="numeric" value="${sim.additionalCosts||''}"><span class="suffix">K</span></div></label><label class="field"><span>${escapeHtml(t(state,'simulation.salePrice'))}</span><div class="input-wrap"><input class="input" data-field="estimatedSalePrice" inputmode="numeric" value="${sim.estimatedSalePrice||''}" aria-invalid="${Boolean(editor.errors?.estimatedSalePrice)}"><span class="suffix">K</span></div>${fieldError(editor,'estimatedSalePrice',state)}</label></div><fieldset class="field"><legend>${escapeHtml(t(state,'simulation.saleChannel'))}</legend><div class="grid-2"><label class="method-card ${sim.estimatedSaleChannel==='Mercado HDV'?'selected':''}"><input type="radio" name="sale-channel" data-field="estimatedSaleChannel" value="Mercado HDV" ${sim.estimatedSaleChannel==='Mercado HDV'?'checked':''}><strong>${escapeHtml(t(state,'simulation.marketChannel'))}</strong><span class="muted small">2%</span></label><label class="method-card ${sim.estimatedSaleChannel==='Outro Jogador'?'selected':''}"><input type="radio" name="sale-channel" data-field="estimatedSaleChannel" value="Outro Jogador" ${sim.estimatedSaleChannel==='Outro Jogador'?'checked':''}><strong>${escapeHtml(t(state,'simulation.playerChannel'))}</strong><span class="muted small">${escapeHtml(t(state,'simulation.noFee'))}</span></label></div></fieldset><div class="kpis"><article class="card kpi"><span>${escapeHtml(t(state,'simulation.upCost'))}</span><strong>${formatCompactKamas(calc.upCost,state.language)}</strong></article><article class="card kpi"><span>${escapeHtml(t(state,'simulation.operationCost'))}</span><strong>${formatCompactKamas(calc.operationCost,state.language)}</strong></article>${calc.fee?`<article class="card kpi"><span>${escapeHtml(t(state,'simulation.marketFee'))}</span><strong>${formatCompactKamas(calc.fee,state.language)}</strong></article>`:''}<article class="card kpi"><span>${escapeHtml(t(state,'simulation.estimatedProfit'))}</span><strong class="${calc.estimatedProfit>0?'positive':calc.estimatedProfit<0?'negative':'zero'}">${formatCompactKamas(calc.estimatedProfit,state.language)}</strong></article></div></div>`;
}

function renderReviewStep(state, editor, calc) {
  const sim=editor.simulation; const c=getCreatureById(sim.creatureId);
  return `<div class="review-grid">${imageTag(c?.imageUrl,c?getCreatureName(c,state.language):sim.creatureCanonicalName,'creature-thumb large')}<div><span class="eyebrow">${escapeHtml(t(state,'simulation.steps.review'))}</span><h2>${escapeHtml(sim.name||`${c?.canonicalName||''} — ${t(state,'simulation.levelRange',{origin:sim.originLevel,target:sim.targetLevel})}`)}</h2><p class="muted">${escapeHtml(t(state,`simulation.${methodKey[sim.upMethod]}`))}</p><div class="review-values" style="margin-top:16px"><div class="metric"><span>${escapeHtml(t(state,'simulation.requiredXp'))}</span><strong>${formatNumber(calc.xpNeeded,state.language,2)} XP</strong></div><div class="metric"><span>${escapeHtml(t(state,'simulation.upCost'))}</span><strong>${formatCompactKamas(calc.upCost,state.language)}</strong></div><div class="metric"><span>${escapeHtml(t(state,'simulation.operationCost'))}</span><strong>${formatCompactKamas(calc.operationCost,state.language)}</strong></div><div class="metric"><span>${escapeHtml(t(state,'simulation.salePrice'))}</span><strong>${formatCompactKamas(calc.salePrice,state.language)}</strong></div>${calc.fee?`<div class="metric"><span>${escapeHtml(t(state,'simulation.marketFee'))}</span><strong>${formatCompactKamas(calc.fee,state.language)}</strong></div>`:''}<div class="metric"><span>${escapeHtml(t(state,'simulation.estimatedProfit'))}</span><strong class="${calc.estimatedProfit>=0?'positive':'negative'}">${formatCompactKamas(calc.estimatedProfit,state.language)}</strong></div></div></div></div>`;
}

export function renderSimulationEditor(state) {
  const editor=state.simulationEditor; const calc=calculateSimulation(editor.simulation);
  const title=editor.mode==='edit'?'editTitle':editor.mode==='duplicate'?'duplicateTitle':'newTitle';
  const bodies=[renderCreatureStep,renderLevelsStep,renderMethodStep,renderCostsStep,renderReviewStep];
  return `<section class="editor-shell"><div class="section-head"><div><span class="eyebrow">${escapeHtml(t(state,'simulation.stepLabel',{current:editor.step,total:5}))}</span><h1>${escapeHtml(t(state,`simulation.${title}`))}</h1></div><button class="button secondary" data-action="exit-editor">${icon('close',17)} ${escapeHtml(t(state,'common.cancel'))}</button></div>${renderStepper(state,editor)}<div class="card editor-panel">${bodies[editor.step-1](state,editor,calc)}<div class="editor-nav"><button class="button secondary" data-action="prev-step" ${editor.step===1?'disabled':''}>${icon('back',17)} ${escapeHtml(t(state,'common.back'))}</button>${editor.step<5?`<button class="button primary" data-action="next-step">${escapeHtml(editor.step===4?t(state,'simulation.reviewSimulation'):t(state,'common.continue'))} ${icon('chevron',17)}</button>`:`<button class="button primary" data-action="save-simulation">${icon('check',17)} ${escapeHtml(editor.mode==='edit'?t(state,'simulation.updateSimulation'):t(state,'simulation.saveSimulation'))}</button>`}</div></div></section>`;
}
